### ISSUE TITLE
Not work `--any --variation 5` on Nicehash

### ISSUE THREAD

**Issue by Quake4** [jceminer/cn_cpu_miner#10]
![image](https://user-images.githubusercontent.com/29517243/41774920-59de683e-762a-11e8-82d5-b32a9695562e.png)
![image](https://user-images.githubusercontent.com/29517243/41774977-930d36a8-762a-11e8-919a-21c7e135bbce.png)

**Comment by Quake4** [comment]
Working well, but showed wrong.

**Comment by jceminer** [comment]
That's documented
```
If JCE fails to detect the coin, force it with --any --variation N (with N as listed below)
and let the miner run. It will still display the wrong coin but mine the good one.
```

However that's very counter-intuitive, so I remove the "v7" note on pools since they now provide several forks (Nicehash was still mono-fork when i started JCE).
Will be in 0.29e
Thanks!

**Comment by Quake4** [comment]
thanks.
