### ISSUE TITLE
Virii Detected

### ISSUE THREAD

**Issue by simulanics** [jceminer/cn_cpu_miner#11]
The executables available for download, have an actual mining virus attached. Do not be misled by the description stating there is another source containing virus'... this is the source containing a virus. Please provide the source as this is an open-source platform. Would like to compile without the virus, thanks! The windows executable contains the Win32/Unwaders.B!ml virus, which is a variant of the D!ml virus.

**DO NOT DOWNLOAD**

**Comment by jceminer** [comment]
There's really no virus/trojan/whatever, but the exe is detected as a virus like any other miner (Claymore, SRB...)
Feel free not to use it if you don't trust, but no need to give false alarms.

The fake releases which are a few kb in a .rar are really trojan, however. JCE release is always several MB in size.

**Comment by jceminer** [comment]
Hello,

The debian package are provided by a user who kindly packed them for me, I "officially" release only in .zip, and the executable in the .zip works fine (it's a standalone executable).

Sure GitHub should be for source and not only binaries, but the Miner "convention" (started by Claymore back in 2014 if i remember well) is to provide help on Bitcointalk and release on Github. SRB does (or did) it too. I'm just following those unformal rules.
Sadly the Mega release exists but **is** a virus some hackers provide disguised into my miner. So if i move to Mega, it would be confusing and suspicious.
