### ISSUE TITLE
StopProcess not supported

### ISSUE THREAD

**Issue by Quake4** [jceminer/cn_cpu_miner#14]
poweshell code:
Stop-Process -Id 12345
miner reported hasexited, but no really exited, still working.

**Comment by jceminer** [comment]
please take a look at
https://github.com/jceminer/cn_cpu_miner/issues/7

the key is to kill the process tree. or use a Posix signal sender
https://github.com/alirdn/windows-kill/releases

instead of the native killer

**Comment by jceminer** [comment]
It should be fixed in the 0.31d GPU. To be backported to CPU version.
Killing the parent now makes the child process stop, period. No need for a Posix-compilant kill signal.

**Comment by Quake4** [comment]
Thanks, this really right work.
