### ISSUE TITLE
Firefox CORB blocking

### ISSUE THREAD

**Issue by SteCoBs** [jceminer/cn_cpu_miner#31]
This is not an issue of miner. Security policies blocks cross domain scripting,
Please add additional header to HTTP server:
Access-Control-Allow-Origin: *
to allow javascript to retreive json data.

**Comment by jceminer** [comment]
Too late for version 0.33k, but right, that will be in the next version. I already updated my code.

**Comment by jceminer** [comment]
I'm waiting to add a new fork but if it takes too long i'll upload the m Linux directly. May you all thank eLvErDe for the Debian packages he provides each time :heart:

**Comment by eLvErDe** [comment]
Not sure so many people use it but still I do it for my own use anyway ;-)

**Comment by SteCoBs** [comment]
Tks man ;)
Works perfect ;)
